theme: jekyll-theme-cayman
title: "SEE-Insight Research Team"
description: "Intelligent Tools for Scientific Image Understanding</p>Department of Computational Mathematics Science and Engineering, Michigan State University"
logo: /images/logo.png

